# Site settings
title: Hysteria
email: zhouhangqing@gmail.com
description: "iOS 应用/游戏工程师一枚，目前在公司写 cocos2d-x ，回家有空就撸点 cocoa 。"
#baseurl: ""
#url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
